<a href="https://colab.research.google.com/github/Karthikh02/IPL-Performance-Analytics-using-Python/blob/main/ipl_EDA_CLEAN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
import kagglehub
path = kagglehub.dataset_download("patrickb1912/ipl-complete-dataset-20082020")

Using Colab cache for faster access to the 'ipl-complete-dataset-20082020' dataset.

In [ ]:
path

'/kaggle/input/ipl-complete-dataset-20082020'

In [ ]:
#Load Dataset
ipl = pd.read_csv('/kaggle/input/ipl-complete-dataset-20082020/matches.csv')

In [ ]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1044 non-null   object
 3   date             1095 non-null   object
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: float64(3), int64(1), object(16)
memory usage: 171.2+ KB

# **DATA CLEANING**

 **We are changing values in season columns values**

In [ ]:
ipl['season'].unique()

array(['2007/08', '2009', '2009/10', '2011', '2012', '2013', '2014',
       '2015', '2016', '2017', '2018', '2019', '2020/21', '2021', '2022',
       '2023', '2024'], dtype=object)

In [ ]:
ipl['season']=ipl['season'].replace({'2007/08':2008,'2009/10':2010,'2020/21':2020})

In [ ]:
ipl['season'].unique()

array([2008, '2009', 2010, '2011', '2012', '2013', '2014', '2015', '2016',
       '2017', '2018', '2019', 2020, '2021', '2022', '2023', '2024'],
      dtype=object)

# **HANDLING NULLVALUES**

# Filling null values in city columns as a UnKnown

In [ ]:
ipl['city']=ipl['city'].fillna('Unknown')


# we are filling normal in method column because in cricket there is 2 chance

1.Normal Method  2.DLS Method(By reducing Over)

In [ ]:
ipl['method'].unique()

array([nan, 'D/L'], dtype=object)

In [ ]:
ipl['method']=ipl['method'].fillna('Normal')


# we are mantaining cities name same because some of the cities having different names

In [ ]:
ipl['city'].unique()

array(['Bangalore', 'Chandigarh', 'Delhi', 'Mumbai', 'Kolkata', 'Jaipur',
       'Hyderabad', 'Chennai', 'Cape Town', 'Port Elizabeth', 'Durban',
       'Centurion', 'East London', 'Johannesburg', 'Kimberley',
       'Bloemfontein', 'Ahmedabad', 'Cuttack', 'Nagpur', 'Dharamsala',
       'Kochi', 'Indore', 'Visakhapatnam', 'Pune', 'Raipur', 'Ranchi',
       'Abu Dhabi', 'Unknown', 'Rajkot', 'Kanpur', 'Bengaluru', 'Dubai',
       'Sharjah', 'Navi Mumbai', 'Lucknow', 'Guwahati', 'Mohali'],
      dtype=object)

In [ ]:
ipl['city']=ipl['city'].replace({'Bangalore':'Bengaluru',
                     'Navi Mumbai':'Mumbai'})

# we are changing team name some team changes there names like 1.rcb 2.pbks 3.delhi etc

In [ ]:
pd.concat([ipl['team1'],ipl['team2']]).unique()

array(['Royal Challengers Bangalore', 'Kings XI Punjab',
       'Delhi Daredevils', 'Mumbai Indians', 'Kolkata Knight Riders',
       'Rajasthan Royals', 'Deccan Chargers', 'Chennai Super Kings',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Gujarat Lions', 'Rising Pune Supergiants',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Lucknow Super Giants', 'Gujarat Titans',
       'Royal Challengers Bengaluru'], dtype=object)

In [ ]:
ipl['team1']=ipl['team1'].replace({'Royal Challengers Bangalore':'Royal Challengers Bengaluru',
                     'Kings XI Punjab':'Punjab Kings',
                     'Delhi Daredevils':'Delhi Capitals',
                     'Deccan Chargers':'Sunrisers Hyderabad',
                     'Pune Warriors':'Rising Pune Supergiants',
                     'Rising Pune Supergiants':'Rising Pune Supergiant'})

In [ ]:
ipl['team2']=ipl['team2'].replace({'Royal Challengers Bangalore':'Royal Challengers Bengaluru',
                     'Kings XI Punjab':'Punjab Kings',
                     'Delhi Daredevils':'Delhi Capitals',
                     'Deccan Chargers':'Sunrisers Hyderabad',
                     'Pune Warriors':'Rising Pune Supergiants',
                     'Rising Pune Supergiants':'Rising Pune Supergiant'})

# we are changing date column exact date datype because previous it is object datatype

In [ ]:
ipl['date']=pd.to_datetime(ipl['date'])

In [ ]:
ipl['season']=ipl['season'].astype(int)

# we are Filling player of match is No award when match was suspended

In [ ]:
ipl['player_of_match']=ipl['player_of_match'].fillna('No Award')

# we are filling winner is no result when match was suspended

In [ ]:
ipl['winner']=ipl['winner'].fillna("No Result")

# we are replacing super_over values with True or False for future operations

In [ ]:
ipl['super_over']=ipl['super_over'].replace({'N':False,'Y':True})

/tmp/ipykernel_4151/3939676690.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ipl['super_over']=ipl['super_over'].replace({'N':False,'Y':True})

# we are changing team name in winner column some team changes there names like 1.rcb 2.pbks 3.delhi etc

In [ ]:
ipl['winner'].unique()

array(['Kolkata Knight Riders', 'Chennai Super Kings', 'Delhi Daredevils',
       'Royal Challengers Bangalore', 'Rajasthan Royals',
       'Kings XI Punjab', 'Deccan Chargers', 'Mumbai Indians',
       'Pune Warriors', 'Kochi Tuskers Kerala', 'No Result',
       'Sunrisers Hyderabad', 'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Gujarat Titans', 'Lucknow Super Giants',
       'Royal Challengers Bengaluru'], dtype=object)

In [ ]:
ipl['winner']=ipl['winner'].replace({'Royal Challengers Bangalore':'Royal Challengers Bengaluru',
                                     'Kings XI Punjab':'Punjab Kings','Pune Warriors':'Rising Pune Supergiant','Rising Pune Supergiants':'Rising Pune Supergiant'})

In [ ]:
ipl['winner'].unique()

array(['Kolkata Knight Riders', 'Chennai Super Kings', 'Delhi Daredevils',
       'Royal Challengers Bengaluru', 'Rajasthan Royals', 'Punjab Kings',
       'Deccan Chargers', 'Mumbai Indians', 'Rising Pune Supergiant',
       'Kochi Tuskers Kerala', 'No Result', 'Sunrisers Hyderabad',
       'Gujarat Lions', 'Delhi Capitals', 'Gujarat Titans',
       'Lucknow Super Giants'], dtype=object)

# **QUESTIONS TO SOLVE**

**1. HOW MANY MATHES ARE THERE IN TOTAL**

In [ ]:
f'Total Macthes In Played In Ipl from 2008 to 2024 is {ipl.shape[0]}'

'Total Macthes In Played In Ipl from 2008 to 2024 is 1095'

**2.HOW MANY SEASONS ARE PRESENT**

In [ ]:
f'Total Seasons Ipl Hosted {ipl['season'].nunique()}'

'Total Seasons Ipl Hosted 16'

**3.HOW MANY UNQIE TEAMS PLAYED IN IPL**

In [ ]:
f'All unquie team played in ipl {pd.concat([ipl['team1'],ipl['team2']]).nunique()}'

'All unquie team played in ipl 14'

**4.WHICH CITIES HOSTED THE MOST MATCHES**

In [ ]:
f'Most Matches Hosted City is {ipl['city'].value_counts().idxmax()}'

'Most Matches Hosted City is Mumbai'

**5.WHAT ARE THE DIFF MATCH TYPES**

In [ ]:
f'Diffrent Matche Types {ipl['match_type'].unique()}'

"Diffrent Matche Types ['League' 'Semi Final' 'Final' '3rd Place Play-Off' 'Qualifier 1'\n 'Elimination Final' 'Qualifier 2' 'Eliminator']"

**6.How many matches are there in total?**

In [ ]:
f'In ipl dataset Mising Cities Values is {ipl['city'][ipl['city']=='Unknown'].size}'

'In ipl dataset Mising Cities Values is 51'

**7.HOW MANY MATCHES WENT TO SUPER OVER**

In [ ]:
f'{ipl['super_over'].sum()} Macthes Super Over Played in Ipl History'

'14 Macthes Super Over Played in Ipl History'

# **Team Analysis**

**8.WHICH TEAM WIN THE MOST MACTHES**

In [ ]:
f'Most wins in the ipl is {ipl['winner'].value_counts().idxmax()} they won {ipl['winner'].value_counts().max()} Matches'

'Most wins in the ipl is Mumbai Indians they won 144 Matches'

**9.WHICH TEAM PLAYED THE MOST MACTHES**

In [ ]:
f'Team That Is Played Most Macthes is {pd.concat([ipl['team1'],ipl['team2']]).value_counts().idxmax()} They Played {pd.concat([ipl['team1'],ipl['team2']]).value_counts().max()} Macthes'

'Team That Is Played Most Macthes is Mumbai Indians They Played 261 Macthes'

**10.WHAT IS THE WIN PERCENTAGE OF EACH TEAMS**

In [ ]:
teams_played=pd.concat([ipl['team1'],ipl['team2']]).value_counts()
teams_wins=ipl['winner'].value_counts()

In [ ]:
win_ratio={}
for team in pd.concat([ipl['team1'],ipl['team2']]).unique():
  win_ratio[team]= teams_wins[team]/teams_played[team]*100

In [ ]:
for key , value in win_ratio.items():
  print(f'{key} Team Win Ratio Is {value}',end='\n')

Royal Challengers Bengaluru Team Win Ratio Is 2.7450980392156863
Punjab Kings Team Win Ratio Is 9.75609756097561
Delhi Capitals Team Win Ratio Is 19.047619047619047
Mumbai Indians Team Win Ratio Is 55.172413793103445
Kolkata Knight Riders Team Win Ratio Is 52.191235059760956
Rajasthan Royals Team Win Ratio Is 50.678733031674206
Sunrisers Hyderabad Team Win Ratio Is 34.24124513618677
Chennai Super Kings Team Win Ratio Is 57.98319327731093
Kochi Tuskers Kerala Team Win Ratio Is 42.857142857142854
Rising Pune Supergiant Team Win Ratio Is 18.867924528301888
Gujarat Lions Team Win Ratio Is 43.333333333333336
Lucknow Super Giants Team Win Ratio Is 54.54545454545454
Gujarat Titans Team Win Ratio Is 62.22222222222222
Rising Pune Supergiants Team Win Ratio Is 21.73913043478261

**11.WHICH TEAM AS THE HIGHEST WIN PERCENTAGE(min 50 matches)**

In [ ]:
f'Which Team Won Most (Min:50 Match) {teams_played[teams_played>50].idxmax()}'

'Which Team Won Most (Min:50 Match) Mumbai Indians'

**12.WHICH TEAM WON THE MOST MATCHES IN SINGLE SEASON**

In [ ]:
f'Most win single season {(ipl.groupby(['season','winner']).size().idxmax())}'

"Most win single season (np.int64(2009), 'Chennai Super Kings')"

In [ ]:
grp = ipl.groupby(['season','winner']).size()
f'Most win single season {grp.idxmax()} with {grp.max()} wins'

"Most win single season (np.int64(2009), 'Chennai Super Kings') with 17 wins"

**13.most wins when team is chose to bat**

In [ ]:
ipl_batdecision=ipl[ipl['toss_decision']=='bat']
ipl_batdecision.groupby('winner').size().idxmax()

'Chennai Super Kings'

In [ ]:
ipl[ipl['toss_decision'] == 'bat']['winner'].value_counts().idxmax()

'Chennai Super Kings'


**14.WHICH TEAM WINS MORE WHEN BATTING FIRST VS CHASING**

In [ ]:
ipl_batdecision=ipl[ipl['toss_decision']=='bat']
f'Most Win Batting First is {ipl_batdecision.groupby('winner').size().idxmax() }'

'Most Win Batting First is Chennai Super Kings'

In [ ]:
ipl_bowldecision=ipl[ipl['toss_decision']=='field']
f'Most Wins When Chasing is {ipl_bowldecision.groupby('winner').size().idxmax()}'

'Most Wins When Chasing is Mumbai Indians'

In [ ]:
better=pd.concat((ipl_batdecision['winner'].value_counts(),ipl_bowldecision['winner'].value_counts()),axis=1)
better.columns=['Bat_First_Wins',"Chasing_wins"]

In [ ]:
better['statargy']=np.where(better['Bat_First_Wins']>better['Chasing_wins'],'Bat','Chase')

In [ ]:
better

                             Bat_First_Wins  Chasing_wins statargy
winner
Chennai Super Kings                    63.0            75    Chase
Mumbai Indians                         54.0            90    Chase
Kolkata Knight Riders                  50.0            81    Chase
Rajasthan Royals                       43.0            69    Chase
Royal Challengers Bangalore            37.0            79    Chase
Sunrisers Hyderabad                    30.0            58    Chase
Delhi Daredevils                       29.0            38    Chase
Kings XI Punjab                        24.0            64    Chase
Deccan Chargers                        14.0            15    Chase
Delhi Capitals                         13.0            35    Chase
Gujarat Titans                          9.0            19    Chase
Pune Warriors                           9.0             3      Bat
Lucknow Super Giants                    6.0            18    Chase
Punjab Kings                            4.0            20    Chase
Gujarat Lions                           2.0            11    Chase
Rising Pune Supergiants                 2.0             3    Chase
No Result                               1.0             4    Chase
Royal Challengers Bengaluru             1.0             6    Chase
Rising Pune Supergiant                  NaN            10    Chase
Kochi Tuskers Kerala                    NaN             6    Chase

In [ ]:
#  Batting First Wins (won by runs)
bat_first = ipl[ipl["result"] == "runs"]

In [ ]:
# Chasing Wins (won by wickets)
chase = ipl[ipl["result"] == "wickets"]

In [ ]:
# -----------------------------
#  Team-wise analysis
# -----------------------------

print("🏏 Batting First Wins (Team-wise):\n")
print(bat_first["winner"].value_counts())

print("\n🎯 Chasing Wins (Team-wise):\n")
print(chase["winner"].value_counts())


#-----------------------------
# 📌 TOTAL COMPARISON
# -----------------------------

print("\n📊 TOTAL WIN COMPARISON:")
print("Batting First Wins:", bat_first.shape[0])
print("Chasing Wins:", chase.shape[0])

🏏 Batting First Wins (Team-wise):

winner
Chennai Super Kings            71
Mumbai Indians                 71
Kolkata Knight Riders          54
Royal Challengers Bangalore    53
Sunrisers Hyderabad            44
Rajasthan Royals               43
Kings XI Punjab                40
Delhi Daredevils               25
Delhi Capitals                 21
Deccan Chargers                18
Lucknow Super Giants           16
Punjab Kings                   11
Gujarat Titans                 11
Pune Warriors                   6
Rising Pune Supergiant          5
Royal Challengers Bengaluru     4
Kochi Tuskers Kerala            2
Rising Pune Supergiants         2
Gujarat Lions                   1
Name: count, dtype: int64

🎯 Chasing Wins (Team-wise):

winner
Kolkata Knight Riders          76
Mumbai Indians                 71
Rajasthan Royals               67
Chennai Super Kings            67
Royal Challengers Bangalore    61
Kings XI Punjab                45
Sunrisers Hyderabad            43
Delhi Daredevils               42
Delhi Capitals                 24
Gujarat Titans                 17
Punjab Kings                   13
Gujarat Lions                  12
Deccan Chargers                11
Lucknow Super Giants            8
Pune Warriors                   6
Rising Pune Supergiant          5
Kochi Tuskers Kerala            4
Rising Pune Supergiants         3
Royal Challengers Bengaluru     3
Name: count, dtype: int64

📊 TOTAL WIN COMPARISON:
Batting First Wins: 498
Chasing Wins: 578

# **Level 2:**

 **How many times did the toss winner also win the match?**

In [ ]:
f'{ipl[ipl['toss_winner']==ipl['winner']].groupby('winner').size().idxmax()} won the toss as well as match most times'

'Mumbai Indians won the toss as well as match most times'

In [ ]:
f'{ipl[ipl['toss_winner']==ipl['winner']].shape[0]} many times toss winner also win the match'

'554 many times toss winner also win the match'

 **What is the toss win → match win percentage?**

In [ ]:
f'toss winer also match win percentage is {round(ipl[ipl['toss_winner']==ipl['winner']].shape[0]/ipl.shape[0]*100,2)} % '

'toss winer also match win percentage is 50.59 % '

In [ ]:
f'{ipl[ipl['toss_winner']!=ipl['winner']].shape[0]} many times toss winner loss the match'

'541 many times toss winner loss the match'

**Which team benefits the most from winning the toss?**

In [ ]:
f'Team that most win toss {ipl['toss_winner'].value_counts().idxmax()}'

'Team that most win toss Mumbai Indians'

**What is the most common toss decision (bat or field)?**

In [ ]:
f'Most repeated decision after winning toss {ipl.groupby('toss_decision').size().idxmax()}'

'Most repeated decision after winning toss field'

In [ ]:
ipl['toss_decision'].value_counts().idxmax()

'field'

# **Level 3**

**Who has the most Player of the Match awards?**

In [ ]:
f'Most Player of the match award goes to {ipl['player_of_match'].value_counts().idxmax()}'

'Most Player of the match award goes to AB de Villiers'

**Top 10 players with most awards**

In [ ]:
print(f'Top 10 Player of the match winners')
print(ipl['player_of_match'].value_counts()[:10])

Top 10 Player of the match winners
player_of_match
AB de Villiers    25
CH Gayle          22
RG Sharma         19
DA Warner         18
V Kohli           18
MS Dhoni          17
RA Jadeja         16
YK Pathan         16
SR Watson         16
AD Russell        15
Name: count, dtype: int64

**Which player has most awards in a single season?**

In [ ]:
grp = ipl.groupby('season')['player_of_match'].value_counts()

print(f"Most Award in single season {grp.idxmax()} with {grp.max()} awards")

Most Award in single season (np.int64(2009), 'SR Tendulkar') with 6 awards

**Which player performs best in finals (if match_type includes finals)?**

In [ ]:
print('There is no single best performer in finals; multiple players have won Player of the Match once each')
print(ipl[ipl['match_type']=='Final']['player_of_match'].value_counts())

There is no single best performer in finals; multiple players have won Player of the Match once each
player_of_match
YK Pathan       1
A Kumble        1
SK Raina        1
M Vijay         1
MS Bisla        1
KA Pollard      1
MK Pandey       1
RG Sharma       1
BCJ Cutting     1
KH Pandya       1
SR Watson       1
JJ Bumrah       1
TA Boult        1
F du Plessis    1
HH Pandya       1
DP Conway       1
MA Starc        1
Name: count, dtype: int64

**Who won the title each season?**

In [ ]:
ipl[ipl['match_type']=='Final'].groupby('season').apply(lambda row:row['winner'].iloc[0])

/tmp/ipykernel_2232/780703849.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  ipl[ipl['match_type']=='Final'].groupby('season').apply(lambda row:row['winner'].iloc[0])

season
2008         Rajasthan Royals
2009          Deccan Chargers
2011      Chennai Super Kings
2012    Kolkata Knight Riders
2013           Mumbai Indians
2014    Kolkata Knight Riders
2015           Mumbai Indians
2016      Sunrisers Hyderabad
2017           Mumbai Indians
2018      Chennai Super Kings
2019           Mumbai Indians
2020           Mumbai Indians
2021      Chennai Super Kings
2022           Gujarat Titans
2023      Chennai Super Kings
2024    Kolkata Knight Riders
dtype: object

In [ ]:
ipl.to_csv('ipl.csv')